# Generated by Django 3.1.1 on 2020-12-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='stages',
        ),
    ]
