# Generated by Django 3.1.1 on 2020-12-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0002_remove_devicedata_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='sNo',
        ),
    ]
